"""WhatsAppHandler — sends WhatsApp alerts via local whatsapp-web.js bridge.

No Docker, no cloud providers, no monthly fees.
The bridge runs in Node.js on localhost:3001 and controls WhatsApp Web directly.

Setup (one-time):
  1. Ensure Node.js is installed (comes with Electron apps).
  2. npm install && npm start in the whatsapp-bridge/ folder.
  3. Open Settings → scan the QR code shown.
  4. Session is saved locally — no QR needed after first scan.
"""

from __future__ import annotations

import threading
import queue
from typing import Any

from loguru import logger

from trace_aml.actions.base import BaseActionHandler
from trace_aml.core.models import ActionTrigger, IncidentRecord


def _fmt_ts(iso: str) -> str:
    if not iso:
        return "—"
    try:
        text = str(iso).strip()
        if text.endswith("Z"):
            text = text[:-1] + "+00:00"
        from datetime import datetime
        dt = datetime.fromisoformat(text)
        return dt.strftime("%Y-%m-%d %H:%M:%S UTC")
    except Exception:
        return str(iso)[:19]


class WhatsAppHandler(BaseActionHandler):
    """Sends WhatsApp alerts via local whatsapp-web.js bridge (Node.js)."""

    def execute(
        self,
        incident: IncidentRecord,
        trigger: ActionTrigger,
        context: dict[str, Any],
    ) -> tuple[bool, str]:
        cfg = self.settings.notifications.whatsapp
        if not cfg.enabled:
            return False, "whatsapp_disabled"
        if not cfg.recipient_numbers:
            return False, "whatsapp_no_recipients"

        pdf_path = context.get("pdf_report_path")
        caption = self._build_caption(incident)

        threading.Thread(
            target=self._send_all,
            args=(cfg, pdf_path, caption),
            daemon=True,
            name=f"wa-{incident.incident_id[-6:]}",
        ).start()
        logger.info(
            "[ACTION:WA] queued for {} recipient(s) (incident {})",
            len(cfg.recipient_numbers),
            incident.incident_id[-8:],
        )
        return True, "whatsapp_queued"

    def execute_sync(
        self,
        incident: IncidentRecord,
        trigger: ActionTrigger,
        context: dict[str, Any],
        timeout: float = 60.0,
    ) -> tuple[bool, str]:
        """Synchronous version for testing — waits for actual delivery."""
        cfg = self.settings.notifications.whatsapp
        if not cfg.enabled:
            return False, "whatsapp_disabled"
        if not cfg.recipient_numbers:
            return False, "whatsapp_no_recipients"

        pdf_path = context.get("pdf_report_path")
        caption = self._build_caption(incident)
        result_queue: queue.Queue[tuple[bool, str | None]] = queue.Queue()

        def send_with_result():
            self._send_all_sync(cfg, pdf_path, caption, result_queue)

        t = threading.Thread(target=send_with_result, daemon=False, name="wa-sync-test")
        t.start()
        t.join(timeout=timeout)

        if t.is_alive():
            return False, "whatsapp_timeout"

        try:
            success, error_reason = result_queue.get(block=False)
            if success:
                return True, "whatsapp_sent"
            return False, error_reason or "whatsapp_failed"
        except queue.Empty:
            return False, "whatsapp_no_result"

    @staticmethod
    def _build_caption(incident: IncidentRecord) -> str:
        severity = str(
            incident.severity.value if hasattr(incident.severity, "value")
            else incident.severity
        ).upper()
        inc_short = incident.incident_id[-8:]
        ts = _fmt_ts(incident.last_seen_time or incident.start_time)
        summary = incident.summary or "—"

        return (
            f"🚨 *TRACE-AML SECURITY ALERT*\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"Incident: `{inc_short}`\n"
            f"Entity:   `{incident.entity_id}`\n"
            f"Severity: *{severity}* ⚠️\n"
            f"Alerts:   {incident.alert_count}\n"
            f"Summary:  {summary[:80]}\n"
            f"Time:     {ts}\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"_Generated by TRACE-AML v4_"
        )

    def _send_all(
        self,
        cfg: Any,
        pdf_path: str | None,
        caption: str,
    ) -> None:
        """Send to every configured recipient (fire-and-forget)."""
        import httpx
        base = cfg.bridge_url.rstrip("/")
        for number in cfg.recipient_numbers:
            clean = number.strip().lstrip("+")
            try:
                if pdf_path and cfg.send_pdf:
                    url = f"{base}/send-media"
                    with open(pdf_path, "rb") as f:
                        files = {"file": (pdf_path.split("/")[-1], f, "application/pdf")}
                        data = {"number": clean, "caption": caption[:1024]}
                        resp = httpx.post(url, data=data, files=files, timeout=60.0)
                        if not resp.is_success:
                            logger.error("[ACTION:WA] PDF bridge error {}: {}", resp.status_code, resp.text)
                        resp.raise_for_status()
                    logger.info("[ACTION:WA] PDF sent to +{}", clean)
                if not (pdf_path and cfg.send_pdf) or cfg.send_text:
                    # Send text: always if no PDF, or also if send_text is checked
                    url = f"{base}/send"
                    payload = {"number": clean, "message": caption}
                    resp = httpx.post(url, json=payload, timeout=15.0)
                    if not resp.is_success:
                        logger.error("[ACTION:WA] text bridge error {}: {}", resp.status_code, resp.text)
                    resp.raise_for_status()
                    logger.info("[ACTION:WA] text sent to +{}", clean)
            except Exception as exc:
                logger.error("[ACTION:WA] failed to send to +{}: {}", clean, exc)

    def _send_all_sync(
        self,
        cfg: Any,
        pdf_path: str | None,
        caption: str,
        result_queue: queue.Queue,
    ) -> None:
        """Synchronous send_all that reports result via queue."""
        import httpx
        base = cfg.bridge_url.rstrip("/")
        success = True
        last_error = None
        for number in cfg.recipient_numbers:
            clean = number.strip().lstrip("+")
            try:
                if pdf_path and cfg.send_pdf:
                    url = f"{base}/send-media"
                    with open(pdf_path, "rb") as f:
                        files = {"file": (pdf_path.split("/")[-1], f, "application/pdf")}
                        data = {"number": clean, "caption": caption[:1024]}
                        resp = httpx.post(url, data=data, files=files, timeout=60.0)
                        logger.info("[ACTION:WA] PDF bridge response: {} - {}", resp.status_code, resp.text)
                        resp.raise_for_status()
                    logger.info("[ACTION:WA] PDF sent to +{}", clean)

                # Always send text when: no PDF, or send_text=true, or PDF failed
                if not (pdf_path and cfg.send_pdf) or cfg.send_text:
                    url = f"{base}/send"
                    payload = {"number": clean, "message": caption}
                    resp = httpx.post(url, json=payload, timeout=15.0)
                    logger.info("[ACTION:WA] text bridge response: {} - {}", resp.status_code, resp.text)
                    resp.raise_for_status()
                    logger.info("[ACTION:WA] text sent to +{}", clean)

            except Exception as exc:
                success = False
                last_error = str(exc)
                logger.error("[ACTION:WA] failed to send to +{}: {}", clean, exc)
        result_queue.put((success, last_error))
