"""WhatsAppHandler — sends WhatsApp alerts via Evolution API (self-hosted).

Integration:
  Evolution API is a Docker/Node.js service that wraps the Baileys protocol.
  This handler calls its REST API to send PDF documents + text captions.

Setup (one-time):
  1. Start Evolution API:
       docker compose -f docker-compose.evolution.yml up -d
     OR (no Docker):
       cd evolution-api && npm run start:prod
  2. Open http://localhost:8081 → create instance → scan QR code with phone.
  3. Set env var: TRACE_AML_WA_API_KEY=your-secret-key
  4. In config.demo.yaml set whatsapp.enabled=true, whatsapp.instance=yournumber@c.us
  5. Test: POST /api/v1/notifications/test/whatsapp

Security:
  - api_key is read from env var TRACE_AML_WA_API_KEY first.
  - The YAML config field is an insecure fallback only.

Threading:
  - HTTP calls run in a background daemon thread.
  - Timeout: 10 seconds per request.
  - On failure: logs error, never raises.
"""

from __future__ import annotations

import os
import threading
from typing import Any

from loguru import logger

from trace_aml.actions.base import BaseActionHandler
from trace_aml.core.models import ActionTrigger, IncidentRecord


def _fmt_ts(iso: str) -> str:
    if not iso:
        return "—"
    try:
        text = str(iso).strip()
        if text.endswith("Z"):
            text = text[:-1] + "+00:00"
        from datetime import datetime
        dt = datetime.fromisoformat(text)
        return dt.strftime("%Y-%m-%d %H:%M:%S UTC")
    except Exception:
        return str(iso)[:19]


class WhatsAppHandler(BaseActionHandler):
    """Sends WhatsApp alerts via Evolution API REST endpoint."""

    def execute(
        self,
        incident: IncidentRecord,
        trigger: ActionTrigger,
        context: dict[str, Any],
    ) -> tuple[bool, str]:
        cfg = self.settings.notifications.whatsapp
        if not cfg.enabled:
            return False, "whatsapp_disabled"

        if not cfg.instance:
            return False, "whatsapp_no_instance"

        if not cfg.recipient_numbers:
            return False, "whatsapp_no_recipients"

        api_key = os.getenv("TRACE_AML_WA_API_KEY", "") or cfg.api_key or ""
        if not api_key:
            return False, "whatsapp_no_api_key"

        pdf_path = context.get("pdf_report_path")
        caption  = self._build_caption(incident)

        # Fire-and-forget in background thread
        threading.Thread(
            target=self._send_all,
            args=(cfg, api_key, pdf_path, caption),
            daemon=True,
            name=f"wa-{incident.incident_id[-6:]}",
        ).start()
        logger.info(
            "[ACTION:WA] queued for {} recipient(s) (incident {})",
            len(cfg.recipient_numbers),
            incident.incident_id[-8:],
        )
        return True, "whatsapp_queued"

    # ── Caption builder ────────────────────────────────────────────────────────

    @staticmethod
    def _build_caption(incident: IncidentRecord) -> str:
        severity = str(
            incident.severity.value if hasattr(incident.severity, "value")
            else incident.severity
        ).upper()
        inc_short = incident.incident_id[-8:]
        ts = _fmt_ts(incident.last_seen_time or incident.start_time)
        summary = incident.summary or "—"

        return (
            f"🚨 *TRACE-AML SECURITY ALERT*\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"Incident: `{inc_short}`\n"
            f"Entity:   `{incident.entity_id}`\n"
            f"Severity: *{severity}* ⚠️\n"
            f"Alerts:   {incident.alert_count}\n"
            f"Summary:  {summary[:80]}\n"
            f"Time:     {ts}\n"
            f"━━━━━━━━━━━━━━━━━━━━\n"
            f"_Generated by TRACE-AML v4_"
        )

    # ── Delivery (background thread) ───────────────────────────────────────────

    def _send_all(
        self,
        cfg: Any,
        api_key: str,
        pdf_path: str | None,
        caption: str,
    ) -> None:
        """Send to every configured recipient number."""
        for number in cfg.recipient_numbers:
            # Normalise — Evolution API wants digits only or E.164 without '+'
            clean_number = number.strip().lstrip("+")
            try:
                if pdf_path and cfg.send_pdf:
                    self._send_media(cfg, api_key, clean_number, pdf_path, caption)
                elif cfg.send_text:
                    self._send_text(cfg, api_key, clean_number, caption)
            except Exception as exc:
                logger.error(
                    "[ACTION:WA] failed to send to {}: {}", clean_number, exc
                )

    def _send_media(
        self,
        cfg: Any,
        api_key: str,
        number: str,
        pdf_path: str,
        caption: str,
    ) -> None:
        """Send PDF document with caption via Evolution API."""
        import httpx, os

        url = f"{cfg.base_url.rstrip('/')}/message/sendMedia/{cfg.instance}"
        headers = {"apikey": api_key}

        with open(pdf_path, "rb") as f:
            filename = os.path.basename(pdf_path)
            resp = httpx.post(
                url,
                headers=headers,
                data={
                    "number":   number,
                    "caption":  caption,
                    "fileName": filename,
                },
                files={"file": (filename, f, "application/pdf")},
                timeout=10.0,
            )
        resp.raise_for_status()
        logger.info(
            "[ACTION:WA] PDF sent to +{} (status {})", number, resp.status_code
        )

    def _send_text(
        self,
        cfg: Any,
        api_key: str,
        number: str,
        text: str,
    ) -> None:
        """Send text-only message via Evolution API."""
        import httpx

        url = f"{cfg.base_url.rstrip('/')}/message/sendText/{cfg.instance}"
        headers = {"apikey": api_key, "Content-Type": "application/json"}

        resp = httpx.post(
            url,
            headers=headers,
            json={"number": number, "text": text},
            timeout=10.0,
        )
        resp.raise_for_status()
        logger.info(
            "[ACTION:WA] text sent to +{} (status {})", number, resp.status_code
        )
